### ISSUE TITLE
Errors in setup.py means installing doesn't work

### ISSUE THREAD

**Issue by boortel** [colinoflynn/pyjtagbs#1]
Hello, it is probably just my misunderstanding, but how should I install the package to conda properly? I created virtual environment in Python 3.8. (32-bit) and I ran the command _python setup.py install_ from the installation directory, which successfully installed the package (no error message risen).

I tested the installation by calling the command _import jtagbs_, which performs well only if I run the Python from the same directory, as the _jtagbs_ package source code is (in console). If I run Python from other directory, or from IDE, the _jtabgs_ package cannot be load and program rises following error:

```
>>> import jtagbs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Anaconda3\envs\ICOP_19_32b\lib\site-packages\jtagbs\__init__.py", line 2, in <module>
    from .viveris.jtagcore import JTAGCore
ModuleNotFoundError: No module named 'jtagbs.viveris'
```

I believe, that I do only some silly mistake, but I cannot find the reason. Could someone please help me with this issue?

Thanks in advance, Sims.

**Comment by boortel** [comment]
Maybe I found the problem - installation creates the directory in the \lib\site-packages\ properly, but it miss the viveris. pylinkbs and bsdlparser folders. If I copy and paste them (especially the viveris folder), import starts working.

**Comment by colinoflynn** [comment]
Oops - I think I fixed this on my own testing & forgot to push it! I've got this on another machine I'll check, as I was using this recently and ran into that exact issue.

Use your hack for now and I'll check on this later, I probably messed up the setup.py.

As a warning this is all ultra-alpha stuff ;-)

**Comment by colinoflynn** [comment]
(Changed name for my own reference to make clear it's a general problem with any install)

**Comment by boortel** [comment]
Great, thank you for a quick response! I will do it in the suggested way, until you commit a fix. It's a thing we have to count with ;)

**Comment by albor66** [comment]
I ran into the same problem, but did not quite understand what and where to copy to make everything work. Could you help me?

**Comment by boortel** [comment]
> I ran into the same problem, but did not quite understand what and where to copy to make everything work. Could you help me?

Sure thing: After you run the installer script setup.py in the selected Python environment, it should create directory called `jtagbs `in the  `\lib\site-packages\` directory of your environment.

Unfortunately, not all library files are transferred during this process, so you have to copy the missing files from the `jtagbs ` directory _downloaded_ from Github to the _newly created_ `jtagbs` directory in your `\lib\site-packages\`. If you won't perform this action, _jtagbs_ library will work only to the restart of your environment.

I had actually no other problems after performing the described process. Let me know, if you would need some more advice.

**Comment by albor66** [comment]
Yes thank you! The error disappeared and everything worked (probably, because I, through inattention, did not notice that it only works with Segger J-link, but I have UsbBlaster)
