### ISSUE TITLE
Note about installation procedures on Windows 10 64-bit

### ISSUE THREAD

**Issue by wuwbobo2021** [colinoflynn/pyjtagbs#8]
Because the 64-bit Windows `libjtagcore` dynamic library doesn't work with `pyjtagbs` (I've tried it but got some "access violation" prompts), I installed the 32-bit Python 3.8 (removed the newer version of 64-bit Python from environment variables). Yes, the Python interpreter must be 32-bit to call a 32-bit DLL directly.

I extracted `pyjtagbs-main.zip`, `cd` into it, executed `pip install .`;

then I tried to run an example, and got this error message:

```
E:\pyjtagbs-main\examples>python testing_connections.py
Traceback (most recent call last):
  File "testing_connections.py", line 4, in <module>
    interface = jtagcore.JTAGCore()
  File "E:\Python38-32\lib\site-packages\jtagbs\viveris\jtagcore.py", line 70, in __init__
    self.lib = windll.LoadLibrary(
  File "E:\Python38-32\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "E:\Python38-32\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

which is hard to understand by itself. Looking into the `jtagcore.py`:
```
            self.lib = windll.LoadLibrary(               
                find_library(liblocation)
            )
```

It probably means `find_library()` returns an empty list, causing the failure in `windll.LoadLibrary()`.

I copied `libjtagcore_x86.dll` (which can also be found at `pyjtagbs-main\jtagbs\viveris`) into `E:\Python38-32\Lib\site-packages\jtagbs\viveris`, and that solved my problem. Is this the recommended way?

PS: It seems like you had been working on switching from `libjtagcore` to your own Python implementation (`jtagraw.py`), but haven't implemented `jtag_rawrw()` which is similar to `jtagcore_push_and_pop_chain()`. Is this crate helpful? <https://docs.rs/jtag-taps/latest/jtag_taps> <https://github.com/PyO3/maturin>

**Comment by XiaoSenLuo** [comment]
I encountered the same problem, unable to load libjtagcore_x64.dll, and fixed the problem by modifying the function call method. The modification can refer to :

``` patch

Subject: [PATCH] support 64bit
---
Index: jtagbs/viveris/jtagcore.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/jtagbs/viveris/jtagcore.py b/jtagbs/viveris/jtagcore.py
--- a/jtagbs/viveris/jtagcore.py	(revision 9ce134d607ea62c1d5888d6140f936fb9c8c54ad)
+++ b/jtagbs/viveris/jtagcore.py	(date 1744877474297)
@@ -41,7 +41,62 @@
         -9:"JTAG_CORE_BAD_CMD",
         -10:"JTAG_CORE_I2C_BUS_NOTFREE"
     }
-
+    _standard_calls_ = [
+        'jtagcore_init',
+        'jtagcore_deinit',
+        'jtagcore_set_logs_callback',
+        'jtagcore_set_logs_level',
+        'jtagcore_get_logs_level',
+        'jtagcore_set_logs_file',
+        'jtagcore_get_logs_file',
+        'jtagcore_get_number_of_probes_drv',
+        'jtagcore_get_number_of_probes',
+        'jtagcore_get_probe_name',
+        'jtagcore_select_and_open_probe',
+        'jtagcore_scan_and_init_chain',
+        'jtagcore_get_number_of_devices',
+        'jtagcore_get_dev_id',
+        'jtagcore_loadbsdlfile',
+        'jtagcore_get_dev_name',
+        'jtagcore_get_bsdl_id',
+        'jtagcore_get_number_of_pins',
+        'jtagcore_get_pin_properties',
+        'jtagcore_get_pin_id',
+        'jtagcore_get_pin_state',
+        'jtagcore_set_pin_state',
+        'jtagcore_set_scan_mode',
+        'jtagcore_push_and_pop_chain',
+        'jtagcore_i2c_set_scl_pin',
+        'jtagcore_i2c_set_sda_pin',
+        'jtagcore_i2c_write_read',
+        'jtagcore_spi_set_cs_pin',
+        'jtagcore_spi_set_clk_pin',
+        'jtagcore_spi_set_miso_pin',
+        'jtagcore_spi_set_mosi_pin',
+        'jtagcore_spi_write_read',
+        'jtagcore_spi_set_bitorder',
+        'jtagcore_mdio_set_mdio_pin',
+        'jtagcore_mdio_set_mdc_pin',
+        'jtagcore_mdio_read',
+        'jtagcore_mdio_write',
+        'jtagcore_memory_clear_pins',
+        'jtagcore_memory_set_address_pin',
+        'jtagcore_memory_set_data_pin',
+        'jtagcore_memory_set_ctrl_pin',
+        'jtagcore_memory_read',
+        'jtagcore_memory_write',
+        'jtagcore_setEnvVar',
+        'jtagcore_getEnvVar',
+        'jtagcore_getEnvVarValue',
+        'jtagcore_getEnvVarIndex',
+        'jtagcore_initScript',
+        'jtagcore_setScriptOutputFunc',
+        'jtagcore_execScriptLine',
+        'jtagcore_execScriptFile',
+        'jtagcore_execScriptRam',
+        'jtagcore_deinitScript',
+        'jtagcore_savePinsStateScript'
+    ]
     INPUT = 1
     OUTPUT = 2
     TRISTATE = 4
@@ -62,26 +117,33 @@
             dirname = os.path.dirname(__file__)
             
             if sys.maxsize > 2**32:
-                raise NotImplementedError("64-bit build doesn't work yet")
-                liblocation = os.path.join(dirname, 'libjtagcore_x64.dll')                
+                # raise NotImplementedError("64-bit build doesn't work yet")
+                liblocation = os.path.join(dirname, 'libjtagcore_x64.dll')
             else:
                 liblocation = os.path.join(dirname, 'libjtagcore_x86.dll')
 
-            self.lib = windll.LoadLibrary(               
-                find_library(liblocation)
-            )
+            # self.lib = windll.LoadLibrary(
+            #     find_library(liblocation)
+            # )
+            self.lib = ctypes.cdll.LoadLibrary(liblocation)
+            if sys.maxsize > 2**32:
+                _winlib = ctypes.windll.LoadLibrary(liblocation)
+                for stdcall in self._standard_calls_:
+                    if hasattr(_winlib, stdcall):
+                        setattr(self.lib, stdcall, getattr(_winlib, stdcall))
+        self.lib.jtagcore_init.restype = ctypes.POINTER(ctypes.c_void_p)
 
-        self._print_callback = CFUNCTYPE(None, POINTER(c_char))(self._loggingprint)
-        
+        self._print_callback = CFUNCTYPE(c_int, POINTER(c_voidp), POINTER(c_char))(self._loggingprint)
+
         self._jtag = self.lib.jtagcore_init()
-        self.lib.jtagcore_set_logs_callback(self._jtag, self._print_callback)
+        # self.lib.jtagcore_set_logs_callback(self._jtag, self._print_callback)
 
     def __del__(self):
         self.deinit()
 
-    def _loggingprint(self, cpoint):
+    def _loggingprint(self, cvoid, cpoint):
         print("hitting callback") #never seen this yet?
-        print(cpoint.value)
+        # print(cpoint.value)
 
     def set_debug_level(self, level):
         """Set level from 0 (verbose) to 4 (little)"""


```
